### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jnthn18/project7#1]
I see a couple things I'd like fixed:

- When I first visit the page, I see a list of red lines. Could you make that not happen?
- Part of the project criteria is that `every form field should always show the current parameters`. It looks like you tried to accomplish this, but it's not really working. I think I know why though. It's very likely that `params[:month]` is a string, while the `month` variable is an integer. [This method](http://apidock.com/ruby/String/to_i) may be useful in fixing this.

Let me know when those problems are resolved and I'll take another look!

**Comment by jnthn18** [comment]
Alright I believe I've fixed both issues you mentioned!

**Comment by chrisvfritz** [comment]
:+1: That looks much better! There are some indentation issues here, mentioned below, that I'd like fixed in future projects. But you can let it be in this one.

## Points of improvement for future projects

### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.

### Inconsistent indentation

I do notice some inconsistent indentation in some files, which I'd like you to try to clean up in future projects. Let me know if you're not sure what I mean or how you'd fix it.
